"""Compatibility shim for routing.

Prefer importing from swarm.runtime.routing going forward.
"""

from swarm.runtime.routing import (
    CELEvaluator,
    ConditionEval,
    DecisionType,
    Edge,
    EdgeCondition,
    FlowGraph,
    NodeConfig,
    RouteContext,
    RouteDecision,
    RoutingContext,
    RoutingResult,
    RunContext,
    SmartRouter,
    StepOutput,
    StepOutputData,
    StepRouter,
    attach_routing_audit,
    convert_to_wp4_explanation,
    create_router,
    emit_routing_event,
    get_router,
    route_from_step,
    route_step,
    store_routing_audit,
)

__all__ = [
    "CELEvaluator",
    "ConditionEval",
    "DecisionType",
    "Edge",
    "EdgeCondition",
    "FlowGraph",
    "NodeConfig",
    "RouteContext",
    "RouteDecision",
    "RoutingContext",
    "RoutingResult",
    "RunContext",
    "SmartRouter",
    "StepOutput",
    "StepOutputData",
    "StepRouter",
    "attach_routing_audit",
    "convert_to_wp4_explanation",
    "create_router",
    "emit_routing_event",
    "get_router",
    "route_from_step",
    "route_step",
    "store_routing_audit",
]
